name: "🐛 Report Bad Contract"
description: Report to us that certain program contract should be repaired.
title: "🐛 [TestRemoval] - <TASK_ID> <WHY>"
labels: ["program contract"]
body:
  - type: input
    id: version
    attributes:
      label: "WildCodeBench version"
      description: What is the version of WildCodeBench? You can find it by running `pip show wildcode`.
      placeholder: For example, 0.1.0
    validations:
      required: true
  - type: input
    id: cache
    attributes:
      label: "Output of running `ls ~/.cache/wildcode`"
    validations:
      required: true
  - type: input
    id: task_id
    attributes:
      label: "Task ID of the programming task"
      placeholder: WildCodeBench/[??]
    validations:
      required: true
  - type: textarea
    id: original
    attributes:
      label: "The original wrong contract"
      description: You can run `python -c "from wildcode.data import get_wild_code_bench print(get_wild_code_bench['WildCodeBench/❓']['contract'])"`
      render: python
    validations:
      required: true
  - type: textarea
    id: new
    attributes:
      label: "Your proposed new contract"
      render: python
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: "Other context"
      description: (Optional) Anything else the maintainer should notice?
    validations:
      required: false
