model_info = {
    "ise-uiuc/Magicoder-S-DS-6.7B": {
        "name": "Magicoder-S-DS-6.7B",
        "link": "https://huggingface.co/ise-uiuc/Magicoder-S-DS-6.7B",
        "prompted": True,
        "size": 6.7,
        "open-data": "Partial",
        },
    "bigcode/starcoder2-15b-instruct-v0.1": {
        "name": "StarCoder2-15B-Instruct-v0.1",
        "link": "https://huggingface.co/bigcode/starcoder2-15b-instruct-v0.1",
        "prompted": True,
        "size": 15,
        "open-data": "Full",
        },
    "bigcode/starcoder2-3b": {
        "name": "StarCoder2-3B",
        "link": "https://huggingface.co/bigcode/starcoder2-3b",
        "prompted": False,
        "size": 3,
        "open-data": "Full",
        },
    "bigcode/starcoder2-7b": {
        "name": "StarCoder2-7B",
        "link": "https://huggingface.co/bigcode/starcoder2-7b",
        "prompted": False,
        "size": 7,
        "open-data": "Full",
        },
    "bigcode/starcoder2-15b": {
        "name": "StarCoder2-15B",
        "link": "https://huggingface.co/bigcode/starcoder2-15b",
        "prompted": False,
        "size": 15,
        "open-data": "Full",
        },
    "Qwen/CodeQwen1.5-7B": {
        "name": "CodeQwen1.5-7B",
        "link": "https://huggingface.co/Qwen/CodeQwen1.5-7B",
        "prompted": False,
        "size": 7,
        "open-data": "None",
        },
    "google/codegemma-2b": {
        "name": "CodeGemma-2B",
        "link": "https://huggingface.co/google/codegemma-2b",
        "prompted": False,
        "size": 2,
        "open-data": "None",
        },
    "google/codegemma-7b": {
        "name": "CodeGemma-7B",
        "link": "https://huggingface.co/google/codegemma-7b",
        "prompted": False,
        "size": 7,
        "open-data": "None",
        },
    "google/codegemma-7b-it": {
        "name": "CodeGemma-7B-Instruct",
        "link": "https://huggingface.co/google/codegemma-7b-it",
        "prompted": True,
        "size": 7,
        "open-data": "None",
        },
    "gpt-3.5-turbo-0125": {
        "name": "GPT-3.5-Turbo-0125",
        "link": "https://openai.com/index/new-embedding-models-and-api-updates",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "gpt-4o": {
        "name": "GPT-4o-2024-05-13",
        "link": "https://openai.com/index/hello-gpt-4o/",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "gpt-4-turbo-2024-04-09": {
        "name": "GPT-4-Turbo-2024-04-09",
        "link": "https://openai.com/blog/new-models-and-developer-products-announced-at-devday",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "gpt-4-0613": {
        "name": "GPT-4-0613",
        "link": "https://openai.com/blog/new-models-and-developer-products-announced-at-devday",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "codellama/CodeLlama-7b-hf": {
        "name": "CodeLlama-7B-Base",
        "link": "https://huggingface.co/codellama/CodeLlama-7b-hf",
        "prompted": False,
        "size": 7,
        "open-data": "None",
        },
    "codellama/CodeLlama-13b-hf": {
        "name": "CodeLlama-13B-Base",
        "link": "https://huggingface.co/codellama/CodeLlama-13b-hf",
        "prompted": False,
        "size": 13,
        "open-data": "None",
        },
    "codellama/CodeLlama-7b-Instruct-hf": {
        "name": "CodeLlama-7B-Instruct",
        "link": "https://huggingface.co/codellama/CodeLlama-7b-Instruct-hf",
        "prompted": True,
        "size": 7,
        "open-data": "None",
        },
    "codellama/CodeLlama-13b-Instruct-hf": {
        "name": "CodeLlama-13B-Instruct",
        "link": "https://huggingface.co/codellama/CodeLlama-13b-Instruct-hf",
        "prompted": True,
        "size": 13,
        "open-data": "None",
        },
    "mistral-large-2402": {
        "name": "Mistral-Large-2402",
        "link": "https://mistral.ai/news/mistral-large/",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "mistral-small-2402": {
        "name": "Mistral-Small-2402",
        "link": "https://mistral.ai/news/mistral-large/",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "mistralai/Mixtral-8x22B-v0.1": {
        "name": "Mixtral-8x22B-Base",
        "link": "https://huggingface.co/mistralai/Mixtral-8x22B-v0.1",
        "prompted": False,
        "size": 44,
        "open-data": "None",
        },
    "mistralai/Mixtral-8x22B-Instruct-v0.1": {
        "name": "Mixtral-8x22B-Instruct",
        "link": "https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1",
        "prompted": True,
        "size": 44,
        "open-data": "None",
        },
    "codellama/CodeLlama-34b-hf": {
        "name": "CodeLlama-34B-Base",
        "link": "https://huggingface.co/codellama/CodeLlama-34b-hf",
        "prompted": False,
        "size": 34,
        "open-data": "None",
        },
    "codellama/CodeLlama-34b-Instruct-hf": {
        "name": "CodeLlama-34B-Instruct",
        "link": "https://huggingface.co/codellama/CodeLlama-34b-Instruct-hf",
        "prompted": True,
        "size": 34,
        "open-data": "None",
        },
    "codellama/CodeLlama-70b-hf": {
        "name": "CodeLlama-70B-Base",
        "link": "https://huggingface.co/codellama/CodeLlama-70b-hf",
        "prompted": False,
        "size": 70,
        "open-data": "None",
        },
    "codellama/CodeLlama-70b-Instruct-hf": {
        "name": "CodeLlama-70B-Instruct",
        "link": "https://huggingface.co/codellama/CodeLlama-70b-Instruct-hf",
        "prompted": True,
        "size": 70,
        "open-data": "None",
        },
    "Qwen/CodeQwen1.5-7B-Chat": {
        "name": "CodeQwen1.5-7B-Chat",
        "link": "https://huggingface.co/Qwen/CodeQwen1.5-7B-Chat",
        "prompted": True,
        "size": 7,
        "open-data": "None",
        },
    "Qwen/Qwen1.5-110B-Chat": {
        "name": "Qwen1.5-110B-Chat",
        "link": "https://huggingface.co/Qwen/Qwen1.5-110B-Chat",
        "prompted": True,
        "size": 110,
        "open-data": "None",
        },
    "Qwen/Qwen1.5-72B-Chat": {
        "name": "Qwen1.5-72B-Chat",
        "link": "https://huggingface.co/Qwen/Qwen1.5-72B-Chat",
        "prompted": True,
        "size": 72,
        "open-data": "None",
        },
    "Qwen/Qwen1.5-32B-Chat": {
        "name": "Qwen1.5-32B-Chat",
        "link": "https://huggingface.co/Qwen/Qwen1.5-32B-Chat",
        "prompted": True,
        "size": 32,
        "open-data": "None",
        },
    "deepseek-ai/DeepSeek-V2-Chat": {
        "name": "DeepSeek-V2-Chat",
        "link": "https://www.deepseek.com/",
        "prompted": True,
        "size": 21,
        "open-data": "None",
        },
    "deepseek-ai/deepseek-coder-1.3b-base": {
        "name": "DeepSeek-Coder-1.3B-Base",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-1.3b-base",
        "prompted": False,
        "size": 1.3,
        "open-data": "None",
        },
    "deepseek-ai/deepseek-coder-1.3b-instruct": {
        "name": "DeepSeek-Coder-1.3B-Instruct",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-1.3b-instruct",
        "prompted": True,
        "size": 1.3,
        "open-data": "None",
        },
    "deepseek-ai/deepseek-coder-33b-base": {
        "name": "DeepSeek-Coder-33B-Base",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-33b-base",
        "prompted": False,
        "size": 33,
        "open-data": "None",
        },
    "deepseek-ai/deepseek-coder-33b-instruct": {
        "name": "DeepSeek-Coder-33B-Instruct",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-33b-instruct",
        "prompted": True,
        "size": 33,
        "open-data": "None",
        },
    "deepseek-ai/deepseek-coder-6.7b-base": {
        "name": "DeepSeek-Coder-6.7B-Base",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base",
        "prompted": False,
        "size": 6.7,
        "open-data": "None",
        },
    "deepseek-ai/deepseek-coder-6.7b-instruct": {
        "name": "DeepSeek-Coder-6.7B-Instruct",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-instruct",
        "prompted": True,
        "size": 6.7,
        "open-data": "None",
        },
    "meta-llama/Meta-Llama-3-70B": {
        "name": "Llama-3-70B-Base",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3-70B",
        "prompted": False,
        "size": 70,
        "open-data": "None",
        },
    "meta-llama/Meta-Llama-3-70B-Instruct": {
        "name": "Llama-3-70B-Instruct",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct",
        "prompted": True,
        "size": 70,
        "open-data": "None",
        },
    "meta-llama/Meta-Llama-3-8B": {
        "name": "Llama-3-8B-Base",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3-8B",
        "prompted": False,
        "size": 8,
        "open-data": "None",
        },
    "meta-llama/Meta-Llama-3-8B-Instruct": {
        "name": "Llama-3-8B-Instruct",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct",
        "prompted": True,
        "size": 8,
        "open-data": "None",
        },
    "ibm-granite/granite-3b-code-instruct": {
        "name": "Granite-Code-3B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-3b-code-instruct",
        "prompted": True,
        "size": 3,
        "open-data": "None",
        },
    "ibm-granite/granite-8b-code-instruct": {
        "name": "Granite-Code-8B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-8b-code-instruct",
        "prompted": True,
        "size": 8,
        "open-data": "None",
        },
    "ibm-granite/granite-20b-code-instruct": {
        "name": "Granite-Code-20B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-20b-code-instruct",
        "prompted": True,
        "size": 20,
        "open-data": "None",
        },
    "ibm-granite/granite-34b-code-instruct": {
        "name": "Granite-Code-34B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-34b-code-instruct",
        "prompted": True,
        "size": 34,
        "open-data": "None",
        },
    "ibm-granite/granite-3b-code-base": {
        "name": "Granite-Code-3B-Base",
        "link": "https://huggingface.co/ibm-granite/granite-3b-code-base",
        "prompted": False,
        "size": 3,
        "open-data": "None",
        },
    "ibm-granite/granite-8b-code-base": {
        "name": "Granite-Code-8B-Base",
        "link": "https://huggingface.co/ibm-granite/granite-8b-code-base",
        "prompted": False,
        "size": 8,
        "open-data": "None",
        },
    "ibm-granite/granite-20b-code-base": {
        "name": "Granite-Code-20B-Base",
        "link": "https://huggingface.co/ibm-granite/granite-20b-code-base",
        "prompted": False,
        "size": 20,
        "open-data": "None",
        },
    "ibm-granite/granite-34b-code-base": {
        "name": "Granite-Code-34B-Base",
        "link": "https://huggingface.co/ibm-granite/granite-34b-code-base",
        "prompted": False,
        "size": 34,
        "open-data": "None",
        },
    "claude-3-haiku-20240307": {
        "name": "Claude-3-Haiku-20240307",
        "link": "https://www.anthropic.com/news/claude-3-family",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "claude-3-sonnet-20240229": {
        "name": "Claude-3-Sonnet-20240229",
        "link": "https://www.anthropic.com/news/claude-3-family",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "claude-3-opus-20240229": {
        "name": "Claude-3-Opus-20240229",
        "link": "https://www.anthropic.com/news/claude-3-family",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "01-ai/Yi-1.5-34B-Chat": {
        "name": "Yi-1.5-34B-Chat",
        "link": "https://huggingface.co/01-ai/Yi-1.5-34B-Chat",
        "prompted": True,
        "size": 34,
        "open-data": "None",
        },
    "01-ai/Yi-1.5-34B": {
        "name": "Yi-1.5-34B",
        "link": "https://huggingface.co/01-ai/Yi-1.5-34B",
        "prompted": False,
        "size": 34,
        "open-data": "None",
        },
    "01-ai/Yi-1.5-9B-Chat": {
        "name": "Yi-1.5-9B-Chat",
        "link": "https://huggingface.co/01-ai/Yi-1.5-9B-Chat",
        "prompted": True,
        "size": 9,
        "open-data": "None",
        },
    "01-ai/Yi-1.5-9B": {
        "name": "Yi-1.5-9B",
        "link": "https://huggingface.co/01-ai/Yi-1.5-9B",
        "prompted": False,
        "size": 9,
        "open-data": "None",
        },
    "01-ai/Yi-1.5-6B-Chat": {
        "name": "Yi-1.5-6B-Chat",
        "link": "https://huggingface.co/01-ai/Yi-1.5-6B-Chat",
        "prompted": True,
        "size": 9,
        "open-data": "None",
        },
    "01-ai/Yi-1.5-6B": {
        "name": "Yi-1.5-6B",
        "link": "https://huggingface.co/01-ai/Yi-1.5-6B",
        "prompted": False,
        "size": 9,
        "open-data": "None",
        },
    "Qwen/Qwen2-57B-A14B": {
        "name": "Qwen2-57B-A14B",
        "link": "https://huggingface.co/Qwen/Qwen2-57B-A14B",
        "prompted": True,
        "size": 14,
        "open-data": "None",
        },
    "Qwen/Qwen2-7B-Instruct": {
        "name": "Qwen2-7B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2-7B-Instruct",
        "prompted": True,
        "size": 7,
        "open-data": "None",
        },
    "Qwen/Qwen2-72B-Chat": {
        "name": "Qwen2-72B-Chat",
        "link": "https://huggingface.co/Qwen/Qwen2-72B-Chat",
        "prompted": True,
        "size": 72,
        "open-data": "None",
        },
    "gemini-1.5-pro": {
        "name": "Gemini-1.5-Pro-API-0514",
        "link": "https://deepmind.google/technologies/gemini/pro",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "gemini-1.5-flash": {
        "name": "Gemini-1.5-Flash-API-0514",
        "link": "https://deepmind.google/technologies/gemini/flash/",
        "prompted": True,
        "size": None,
        "open-data": "None",
        },
    "m-a-p/OpenCodeInterpreter-DS-33B": {
        "name": "OpenCodeInterpreter-DS-33B",
        "link": "https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-33B",
        "prompted": True,
        "size": 33,
        "open-data": "Partial",
        },
    "m-a-p/OpenCodeInterpreter-DS-6.7B": {
        "name": "OpenCodeInterpreter-DS-6.7B",
        "link": "https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-6.7B",
        "prompted": True,
        "size": 6.7,
        "open-data": "Partial",
        },
    "m-a-p/OpenCodeInterpreter-DS-1.3B": {
        "name": "OpenCodeInterpreter-DS-1.3B",
        "link": "https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-1.3B",
        "prompted": True,
        "size": 1.3,
        "open-data": "Partial",
        },
    "microsoft/Phi-3-medium-128k-instruct": {
        "name": "Phi-3-medium-128k-instruct",
        "link": "https://huggingface.co/microsoft/Phi-3-medium-128k-instruct",
        "prompted": True,
        "size": 14,
        "open-data": "None",
        },
    "microsoft/Phi-3-small-128k-instruct": {
        "name": "Phi-3-small-128k-instruct",
        "link": "https://huggingface.co/microsoft/Phi-3-small-128k-instruct",
        "prompted": True,
        "size": 7,
        "open-data": "None",
        },
    "mistralai/Codestral-22B-v0.1": {
        "name": "Codestral-22B-v0.1",
        "link": "https://huggingface.co/mistralai/Codestral-22B-v0.1",
        "prompted": True,
        "size": 22,
        "open-data": "None",
        },
    "mistralai/Mistral-7B-Instruct-v0.3": {
        "name": "Mistral-7B-Instruct-v0.3",
        "link": "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
        "prompted": True,
        "size": 7,
        "open-data": "None",
        },
    "mistralai/Mistral-7B-v0.3": {
        "name": "Mistral-7B-v0.3",
        "link": "https://huggingface.co/mistralai/Mistral-7B-v0.3",
        "prompted": False,
        "size": 7,
        "open-data": "None",
        },
    "CohereForAI/c4ai-command-r-plus": {
        "name": "Command R+",
        "link": "https://huggingface.co/CohereForAI/c4ai-command-r-plus",
        "prompted": True,
        "size": 104,
        "open-data": "None",
    },
    "deepseek-coder": {
        "name": "DeepSeek-Coder-V2-Instruct",
        "link": "https://www.deepseek.com/",
        "prompted": True,
        "size": 21,
        "open-data": "None",
    },
    "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct": {
        "name": "DeepSeek-Coder-V2-Lite-Instruct",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
        "prompted": True,
        "size": 2.4,
        "open-data": "None",
    },
    "deepseek-ai/DeepSeek-Coder-V2-Lite-Base": {
        "name": "DeepSeek-Coder-V2-Lite-Base",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Base",
        "prompted": False,
        "size": 2.4,
        "open-data": "None",
    },
    "claude-3-5-sonnet-20240620": {
        "name": "Claude-3.5-Sonnet-20240620",
        "link": "https://claude.ai/",
        "prompted": True,
        "size": None,
        "open-data": "None",
    },
    "NousResearch/Hermes-2-Theta-Llama-3-70B": {
        "name": "Hermes-2-Theta-Llama-3-70B",
        "link": "https://huggingface.co/NousResearch/Hermes-2-Theta-Llama-3-70B",
        "prompted": True,
        "size": 70,
        "open-data": "None",
    },
    "microsoft/wavecoder-ultra-6.7b": {
        "name": "WaveCoder-Ultra-6.7B",
        "link": "https://huggingface.co/microsoft/wavecoder-ultra-6.7b",
        "prompted": True,
        "size": 6.7,
        "open-data": "None",
    },
    "google/gemma-2-9b-it": {
        "name": "Gemma-2-9B-Instruct",
        "link": "https://huggingface.co/google/gemma-2-9b-it",
        "prompted": True,
        "size": 9,
        "open-data": "None",
    },
    "Bin12345/AutoCoder": {
        "name": "AutoCoder",
        "link": "https://huggingface.co/Bin12345/AutoCoder",
        "prompted": True,
        "size": 33,
        "open-data": "None",
    },
    "Bin12345/AutoCoder_S_6.7B": {
        "name": "AutoCoder-S-6.7B",
        "link": "https://huggingface.co/Bin12345/AutoCoder_S_6.7B",
        "prompted": True,
        "size": 6.7,
        "open-data": "None",
    },
    "Bin12345/AutoCoder_QW_7B": {
        "name": "AutoCoder-QW-7B",
        "link": "https://huggingface.co/Bin12345/AutoCoder_QW_7B",
        "prompted": True,
        "size": 7,
        "open-data": "None",
    },
}