model_info = {
    "ise-uiuc/Magicoder-S-DS-6.7B": {
        "name": "Magicoder-S-DS-6.7B",
        "link": "https://huggingface.co/ise-uiuc/Magicoder-S-DS-6.7B",
        "prompted": True,
        "moe": False,
        "size": 6.7,
        "act_param": 6.7,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-12-04",
    },
    "bigcode/starcoder2-15b-instruct-v0.1": {
        "name": "StarCoder2-15B-Instruct-v0.1",
        "link": "https://huggingface.co/bigcode/starcoder2-15b-instruct-v0.1",
        "prompted": True,
        "moe": False,
        "size": 15,
        "act_param": 15,
        "open-data": "Full",
        "reasoning": False,
        "date": "2024-04-30"
    },
    "bigcode/starcoder2-3b": {
        "name": "StarCoder2-3B",
        "link": "https://huggingface.co/bigcode/starcoder2-3b",
        "prompted": False,
        "moe": False,
        "size": 3,
        "act_param": 3,
        "open-data": "Full",
        "reasoning": False,
        "date": "2024-02-29"
    },
    "bigcode/starcoder2-7b": {
        "name": "StarCoder2-7B",
        "link": "https://huggingface.co/bigcode/starcoder2-7b",
        "prompted": False,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "Full",
        "reasoning": False,
        "date": "2024-02-29"
    },
    "bigcode/starcoder2-15b": {
        "name": "StarCoder2-15B",
        "link": "https://huggingface.co/bigcode/starcoder2-15b",
        "prompted": False,
        "moe": False,
        "size": 15,
        "act_param": 15,
        "open-data": "Full",
        "reasoning": False,
        "date": "2024-02-29"
    },
    "Qwen/CodeQwen1.5-7B": {
        "name": "CodeQwen1.5-7B",
        "link": "https://huggingface.co/Qwen/CodeQwen1.5-7B",
        "prompted": False,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-16"
    },
    "google/codegemma-2b": {
        "name": "CodeGemma-2B",
        "link": "https://huggingface.co/google/codegemma-2b",
        "prompted": False,
        "moe": False,
        "size": 2,
        "act_param": 2,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-10"
    },
    "google/codegemma-7b": {
        "name": "CodeGemma-7B",
        "link": "https://huggingface.co/google/codegemma-7b",
        "prompted": False,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-10"
    },
    "google/codegemma-7b-it": {
        "name": "CodeGemma-7B-Instruct",
        "link": "https://huggingface.co/google/codegemma-7b-it",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-10"
    },
    "gpt-3.5-turbo-0125": {
        "name": "GPT-3.5-Turbo-0125",
        "link": "https://openai.com/index/new-embedding-models-and-api-updates",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-01-25"
    },
    "gpt-4o": {
        "name": "GPT-4o-2024-05-13",
        "link": "https://openai.com/index/hello-gpt-4o/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-13"
    },
    "gpt-4-turbo-2024-04-09": {
        "name": "GPT-4-Turbo-2024-04-09",
        "link": "https://openai.com/blog/new-models-and-developer-products-announced-at-devday",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-09"
    },
    "gpt-4-0613": {
        "name": "GPT-4-0613",
        "link": "https://openai.com/blog/new-models-and-developer-products-announced-at-devday",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-06-13"
    },
    "codellama/CodeLlama-7b-hf": {
        "name": "CodeLlama-7B-Base",
        "link": "https://huggingface.co/codellama/CodeLlama-7b-hf",
        "prompted": False,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-08-25"
    },
    "codellama/CodeLlama-13b-hf": {
        "name": "CodeLlama-13B-Base",
        "link": "https://huggingface.co/codellama/CodeLlama-13b-hf",
        "prompted": False,
        "moe": False,
        "size": 13,
        "act_param": 13,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-08-25"
    },
    "codellama/CodeLlama-7b-Instruct-hf": {
        "name": "CodeLlama-7B-Instruct",
        "link": "https://huggingface.co/codellama/CodeLlama-7b-Instruct-hf",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-08-25"
    },
    "codellama/CodeLlama-13b-Instruct-hf": {
        "name": "CodeLlama-13B-Instruct",
        "link": "https://huggingface.co/codellama/CodeLlama-13b-Instruct-hf",
        "prompted": True,
        "moe": False,
        "size": 13,
        "act_param": 13,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-08-25"
    },
    "mistral-large-2402": {
        "name": "Mistral-Large-2402",
        "link": "https://mistral.ai/news/mistral-large/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-02-26"
    },
    "mistral-small-2402": {
        "name": "Mistral-Small-2402",
        "link": "https://mistral.ai/news/mistral-large/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-02-26"
    },
    "mistralai/Mixtral-8x22B-v0.1": {
        "name": "Mixtral-8x22B-Base",
        "link": "https://huggingface.co/mistralai/Mixtral-8x22B-v0.1",
        "prompted": False,
        "moe": True,
        "size": 176,
        "act_param": 44,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-17"
    },
    "mistralai/Mixtral-8x22B-Instruct-v0.1": {
        "name": "Mixtral-8x22B-Instruct",
        "link": "https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1",
        "prompted": True,
        "moe": False,
        "size": 176,
        "act_param": 44,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-17"
    },
    "codellama/CodeLlama-34b-hf": {
        "name": "CodeLlama-34B-Base",
        "link": "https://huggingface.co/codellama/CodeLlama-34b-hf",
        "prompted": False,
        "moe": False,
        "size": 34,
        "act_param": 34,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-08-25"
    },
    "codellama/CodeLlama-34b-Instruct-hf": {
        "name": "CodeLlama-34B-Instruct",
        "link": "https://huggingface.co/codellama/CodeLlama-34b-Instruct-hf",
        "prompted": True,
        "moe": False,
        "size": 34,
        "act_param": 34,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-08-25"
    },
    "codellama/CodeLlama-70b-hf": {
        "name": "CodeLlama-70B-Base",
        "link": "https://huggingface.co/codellama/CodeLlama-70b-hf",
        "prompted": False,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-08-25"
    },
    "codellama/CodeLlama-70b-Instruct-hf": {
        "name": "CodeLlama-70B-Instruct",
        "link": "https://huggingface.co/codellama/CodeLlama-70b-Instruct-hf",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-08-25"
    },
    "Qwen/CodeQwen1.5-7B-Chat": {
        "name": "CodeQwen1.5-7B-Chat",
        "link": "https://huggingface.co/Qwen/CodeQwen1.5-7B-Chat",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-16"
    },
    "Qwen/Qwen1.5-110B-Chat": {
        "name": "Qwen1.5-110B-Chat",
        "link": "https://huggingface.co/Qwen/Qwen1.5-110B-Chat",
        "prompted": True,
        "moe": False,
        "size": 110,
        "act_param": 110,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-26"
    },
    "Qwen/Qwen1.5-72B-Chat": {
        "name": "Qwen1.5-72B-Chat",
        "link": "https://huggingface.co/Qwen/Qwen1.5-72B-Chat",
        "prompted": True,
        "moe": False,
        "size": 72,
        "act_param": 72,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-26"
    },
    "Qwen/Qwen1.5-32B-Chat": {
        "name": "Qwen1.5-32B-Chat",
        "link": "https://huggingface.co/Qwen/Qwen1.5-32B-Chat",
        "prompted": True,
        "moe": False,
        "size": 32,
        "act_param": 32,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-26"
    },
    "deepseek-ai/DeepSeek-V2-Chat": {
        "name": "DeepSeek-V2-Chat",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-V2-Chat",
        "prompted": True,
        "moe": True,
        "size": 236,
        "act_param": 21,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-06"
    },
    "deepseek-ai/deepseek-coder-1.3b-base": {
        "name": "DeepSeek-Coder-1.3B-Base",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-1.3b-base",
        "prompted": False,
        "moe": False,
        "size": 1.3,
        "act_param": 1.3,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-10-28"
    },
    "deepseek-ai/deepseek-coder-1.3b-instruct": {
        "name": "DeepSeek-Coder-1.3B-Instruct",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-1.3b-instruct",
        "prompted": True,
        "moe": False,
        "size": 1.3,
        "act_param": 1.3,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-10-28"
    },
    "deepseek-ai/deepseek-coder-33b-base": {
        "name": "DeepSeek-Coder-33B-Base",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-33b-base",
        "prompted": False,
        "moe": False,
        "size": 33,
        "act_param": 33,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-10-28"
    },
    "deepseek-ai/deepseek-coder-33b-instruct": {
        "name": "DeepSeek-Coder-33B-Instruct",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-33b-instruct",
        "prompted": True,
        "moe": False,
        "size": 33,
        "act_param": 33,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-10-28"
    },
    "deepseek-ai/deepseek-coder-6.7b-base": {
        "name": "DeepSeek-Coder-6.7B-Base",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base",
        "prompted": False,
        "moe": False,
        "size": 6.7,
        "act_param": 6.7,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-10-28"
    },
    "deepseek-ai/deepseek-coder-6.7b-instruct": {
        "name": "DeepSeek-Coder-6.7B-Instruct",
        "link": "https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-instruct",
        "prompted": True,
        "moe": False,
        "size": 6.7,
        "act_param": 6.7,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-10-28"
    },
    "meta-llama/Meta-Llama-3-70B": {
        "name": "Llama-3-70B-Base",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3-70B",
        "prompted": False,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-18"
    },
    "meta-llama/Meta-Llama-3-70B-Instruct": {
        "name": "Llama-3-70B-Instruct",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-18"
    },
    "meta-llama/Meta-Llama-3-8B": {
        "name": "Llama-3-8B-Base",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3-8B",
        "prompted": False,
        "moe": False,
        "size": 8,
        "act_param": 8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-18"
    },
    "meta-llama/Meta-Llama-3-8B-Instruct": {
        "name": "Llama-3-8B-Instruct",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 8,
        "act_param": 8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-18"
    },
    "ibm-granite/granite-3b-code-instruct": {
        "name": "Granite-Code-3B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-3b-code-instruct",
        "prompted": True,
        "moe": False,
        "size": 3,
        "act_param": 3,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-06"
    },
    "ibm-granite/granite-8b-code-instruct": {
        "name": "Granite-Code-8B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-8b-code-instruct",
        "prompted": True,
        "moe": False,
        "size": 8,
        "act_param": 8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-06"
    },
    "ibm-granite/granite-20b-code-instruct": {
        "name": "Granite-Code-20B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-20b-code-instruct",
        "prompted": True,
        "moe": False,
        "size": 20,
        "act_param": 20,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-06"
    },
    "ibm-granite/granite-34b-code-instruct": {
        "name": "Granite-Code-34B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-34b-code-instruct",
        "prompted": True,
        "moe": False,
        "size": 34,
        "act_param": 34,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-06"
    },
    "ibm-granite/granite-3b-code-base": {
        "name": "Granite-Code-3B-Base",
        "link": "https://huggingface.co/ibm-granite/granite-3b-code-base",
        "prompted": False,
        "moe": False,
        "size": 3,
        "act_param": 3,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-06"
    },
    "ibm-granite/granite-8b-code-base": {
        "name": "Granite-Code-8B-Base",
        "link": "https://huggingface.co/ibm-granite/granite-8b-code-base",
        "prompted": False,
        "moe": False,
        "size": 8,
        "act_param": 8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-06"
    },
    "ibm-granite/granite-20b-code-base": {
        "name": "Granite-Code-20B-Base",
        "link": "https://huggingface.co/ibm-granite/granite-20b-code-base",
        "prompted": False,
        "moe": False,
        "size": 20,
        "act_param": 20,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-06"
    },
    "ibm-granite/granite-34b-code-base": {
        "name": "Granite-Code-34B-Base",
        "link": "https://huggingface.co/ibm-granite/granite-34b-code-base",
        "prompted": False,
        "moe": False,
        "size": 34,
        "act_param": 34,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-06"
    },
    "claude-3-haiku-20240307": {
        "name": "Claude-3-Haiku-20240307",
        "link": "https://www.anthropic.com/news/claude-3-family",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-03-07"
    },
    "claude-3-sonnet-20240229": {
        "name": "Claude-3-Sonnet-20240229",
        "link": "https://www.anthropic.com/news/claude-3-family",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-02-29"
    },
    "claude-3-opus-20240229": {
        "name": "Claude-3-Opus-20240229",
        "link": "https://www.anthropic.com/news/claude-3-family",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-02-29"
    },
    "01-ai/Yi-1.5-34B-Chat": {
        "name": "Yi-1.5-34B-Chat",
        "link": "https://huggingface.co/01-ai/Yi-1.5-34B-Chat",
        "prompted": True,
        "moe": False,
        "size": 34,
        "act_param": 34,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-20"
    },
    "01-ai/Yi-1.5-34B": {
        "name": "Yi-1.5-34B",
        "link": "https://huggingface.co/01-ai/Yi-1.5-34B",
        "prompted": False,
        "moe": False,
        "size": 34,
        "act_param": 34,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-20"
    },
    "01-ai/Yi-1.5-9B-Chat": {
        "name": "Yi-1.5-9B-Chat",
        "link": "https://huggingface.co/01-ai/Yi-1.5-9B-Chat",
        "prompted": True,
        "moe": False,
        "size": 9,
        "act_param": 9,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-20"
    },
    "01-ai/Yi-1.5-9B": {
        "name": "Yi-1.5-9B",
        "link": "https://huggingface.co/01-ai/Yi-1.5-9B",
        "prompted": False,
        "moe": False,
        "size": 9,
        "act_param": 9,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-20"
    },
    "01-ai/Yi-1.5-6B-Chat": {
        "name": "Yi-1.5-6B-Chat",
        "link": "https://huggingface.co/01-ai/Yi-1.5-6B-Chat",
        "prompted": True,
        "moe": False,
        "size": 6,
        "act_param": 6,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-20"
    },
    "01-ai/Yi-1.5-6B": {
        "name": "Yi-1.5-6B",
        "link": "https://huggingface.co/01-ai/Yi-1.5-6B",
        "prompted": False,
        "moe": False,
        "size": 6,
        "act_param": 6,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-20"
    },
    "Qwen/Qwen2-57B-A14B": {
        "name": "Qwen2-57B-A14B",
        "link": "https://huggingface.co/Qwen/Qwen2-57B-A14B",
        "prompted": True,
        "moe": True,
        "size": 57,
        "act_param": 14,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-06-07"
    },
    "Qwen/Qwen2-7B-Instruct": {
        "name": "Qwen2-7B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2-7B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-06-07"
    },
    "Qwen/Qwen2-72B-Chat": {
        "name": "Qwen2-72B-Chat",
        "link": "https://huggingface.co/Qwen/Qwen2-72B-Chat",
        "prompted": True,
        "moe": False,
        "size": 72,
        "act_param": 72,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-06-07"
    },
    "gemini-1.5-pro": {
        "name": "Gemini-1.5-Pro-API-0514",
        "link": "https://deepmind.google/technologies/gemini/pro",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-14"
    },
    "gemini-1.5-flash": {
        "name": "Gemini-1.5-Flash-API-0514",
        "link": "https://deepmind.google/technologies/gemini/flash/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-14"
    },
    "m-a-p/OpenCodeInterpreter-DS-33B": {
        "name": "OpenCodeInterpreter-DS-33B",
        "link": "https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-33B",
        "prompted": True,
        "moe": False,
        "size": 33,
        "act_param": 33,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-02-22"
    },
    "m-a-p/OpenCodeInterpreter-DS-6.7B": {
        "name": "OpenCodeInterpreter-DS-6.7B",
        "link": "https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-6.7B",
        "prompted": True,
        "moe": False,
        "size": 6.7,
        "act_param": 6.7,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-02-22"
    },
    "m-a-p/OpenCodeInterpreter-DS-1.3B": {
        "name": "OpenCodeInterpreter-DS-1.3B",
        "link": "https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-1.3B",
        "prompted": True,
        "moe": False,
        "size": 1.3,
        "act_param": 1.3,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-02-22"
    },
    "microsoft/Phi-3-medium-128k-instruct": {
        "name": "Phi-3-Medium-128K-Instruct",
        "link": "https://huggingface.co/microsoft/Phi-3-medium-128k-instruct",
        "prompted": True,
        "moe": False,
        "size": 14,
        "act_param": 14,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-21"
    },
    "microsoft/Phi-3-small-128k-instruct": {
        "name": "Phi-3-Small-128K-Instruct",
        "link": "https://huggingface.co/microsoft/Phi-3-small-128k-instruct",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-21"
    },
    "codestral-2405": {
        "name": "Codestral-22B-v0.1",
        "link": "https://huggingface.co/mistralai/Codestral-22B-v0.1",
        "prompted": True,
        "moe": False,
        "size": 22,
        "act_param": 22,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-23"
    },
    "codestral-mamba-2407": {
        "name": "Codestral-Mamba",
        "link": "https://huggingface.co/mistralai/mamba-codestral-7B-v0.1",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-16"
    },
    "mistralai/Mistral-7B-Instruct-v0.3": {
        "name": "Mistral-7B-Instruct-v0.3",
        "link": "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-22"
    },
    "mistralai/Mistral-7B-v0.3": {
        "name": "Mistral-7B-v0.3",
        "link": "https://huggingface.co/mistralai/Mistral-7B-v0.3",
        "prompted": False,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-22"
    },
    "CohereForAI/c4ai-command-r-plus": {
        "name": "Command R+",
        "link": "https://huggingface.co/CohereForAI/c4ai-command-r-plus",
        "prompted": True,
        "moe": False,
        "size": 104,
        "act_param": 104,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-04"
    },
    "deepseek-coder": {
        "name": "DeepSeek-Coder-V2-Instruct",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Instruct",
        "prompted": True,
        "moe": True,
        "size": 236,
        "act_param": 21,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-06-17"
    },
    "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct": {
        "name": "DeepSeek-Coder-V2-Lite-Instruct",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
        "prompted": True,
        "moe": True,
        "size": 16,
        "act_param": 2.4,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-06-17"
    },
    "deepseek-ai/DeepSeek-Coder-V2-Lite-Base": {
        "name": "DeepSeek-Coder-V2-Lite-Base",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Base",
        "prompted": False,
        "moe": True,
        "size": 16,
        "act_param": 2.4,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-06-17"
    },
    "claude-3-5-sonnet-20240620": {
        "name": "Claude-3.5-Sonnet-20240620",
        "link": "https://claude.ai/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-06-20"
    },
    "NousResearch/Hermes-2-Theta-Llama-3-70B": {
        "name": "Hermes-2-Theta-Llama-3-70B",
        "link": "https://huggingface.co/NousResearch/Hermes-2-Theta-Llama-3-70B",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-06-24"
    },
    "microsoft/wavecoder-ultra-6.7b": {
        "name": "WaveCoder-Ultra-6.7B",
        "link": "https://huggingface.co/microsoft/wavecoder-ultra-6.7b",
        "prompted": True,
        "moe": False,
        "size": 6.7,
        "act_param": 6.7,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-12-26"
    },
    "google/gemma-2-9b-it": {
        "name": "Gemma-2-9B-Instruct",
        "link": "https://huggingface.co/google/gemma-2-9b-it",
        "prompted": True,
        "moe": False,
        "size": 9,
        "act_param": 9,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-06-19"
    },
    "Bin12345/AutoCoder": {
        "name": "AutoCoder",
        "link": "https://huggingface.co/Bin12345/AutoCoder",
        "prompted": True,
        "moe": False,
        "size": 33,
        "act_param": 33,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-23"
    },
    "Bin12345/AutoCoder_S_6.7B": {
        "name": "AutoCoder-S-6.7B",
        "link": "https://huggingface.co/Bin12345/AutoCoder_S_6.7B",
        "prompted": True,
        "moe": False,
        "size": 6.7,
        "act_param": 6.7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-23"
    },
    "Bin12345/AutoCoder_QW_7B": {
        "name": "AutoCoder-QW-7B",
        "link": "https://huggingface.co/Bin12345/AutoCoder_QW_7B",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-23"
    },
    "SenseLLM/ReflectionCoder-DS-33B": {
        "name": "ReflectionCoder-DS-33B",
        "link": "https://huggingface.co/SenseLLM/ReflectionCoder-DS-33B",
        "prompted": True,
        "moe": False,
        "size": 33,
        "act_param": 33,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-05-27"
    },
    "SenseLLM/ReflectionCoder-DS-6.7B": {
        "name": "ReflectionCoder-DS-6.7B",
        "link": "https://huggingface.co/SenseLLM/ReflectionCoder-DS-6.7B",
        "prompted": True,
        "moe": False,
        "size": 6.7,
        "act_param": 6.7,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-05-27"
    },
    "SenseLLM/ReflectionCoder-CL-34B": {
        "name": "ReflectionCoder-CL-34B",
        "link": "https://huggingface.co/SenseLLM/ReflectionCoder-CL-34B",
        "prompted": True,
        "moe": False,
        "size": 34,
        "act_param": 34,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-05-27"
    },
    "SenseLLM/ReflectionCoder-CL-7B": {
        "name": "ReflectionCoder-CL-7B",
        "link": "https://huggingface.co/SenseLLM/ReflectionCoder-CL-7B",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-05-27"
    },
    "new-microsoft/Phi-3-mini-128k-instruct": {
        "name": "Phi-3.1-Mini-128K-Instruct",
        "link": "https://huggingface.co/microsoft/Phi-3-mini-128k-instruct",
        "prompted": True,
        "moe": False,
        "size": 3.8,
        "act_param": 3.8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-21"
    },
    "old-microsoft/Phi-3-mini-128k-instruct": {
        "name": "Phi-3-Mini-128K-Instruct",
        "link": "https://huggingface.co/microsoft/Phi-3-mini-128k-instruct",
        "prompted": True,
        "moe": False,
        "size": 3.8,
        "act_param": 3.8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-21"
    },
    "internlm/internlm2_5-7b-chat": {
        "name": "InternLM2.5-7B-Chat",
        "link": "https://huggingface.co/internlm/internlm2_5-7b-chat",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-03"
    },
    "NousResearch/Hermes-2-Pro-Llama-3-70B": {
        "name": "Hermes-2-Pro-Llama-3-70B",
        "link": "https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-70B",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-06-27"
    },
    "new-deepseek-chat": {
        "name": "DeepSeek-V2-Chat (2024-06-28)",
        "link": "https://www.deepseek.com/",
        "prompted": True,
        "moe": True,
        "size": 236,
        "act_param": 21,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-06-28"
    },
    "vllm-google/gemma-2-27b-it": {
        "name": "Gemma-2-27B-Instruct",
        "link": "https://huggingface.co/google/gemma-2-27b-it",
        "prompted": True,
        "moe": False,
        "size": 27,
        "act_param": 27,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-06-19"
    },
    "Artigenz/Artigenz-Coder-DS-6.7B": {
        "name": "Artigenz-Coder-DS-6.7B",
        "link": "https://huggingface.co/Artigenz/Artigenz-Coder-DS-6.7B",
        "prompted": True,
        "moe": False,
        "size": 6.7,
        "act_param": 6.7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-16"
    },
    "openchat/openchat-3.6-8b-20240522": {
        "name": "OpenChat-3.6-8B-20240522",
        "link": "https://huggingface.co/openchat/openchat-3.6-8b-20240522",
        "prompted": True,
        "moe": False,
        "size": 8,
        "act_param": 8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-22"
    },
    "Phind/Phind-CodeLlama-34B-v2": {
        "name": "Phind-CodeLlama-34B-v2",
        "link": "https://huggingface.co/Phind/Phind-CodeLlama-34B-v2",
        "prompted": True,
        "moe": False,
        "size": 34,
        "act_param": 34,
        "open-data": "None",
        "reasoning": False,
        "date": "2023-08-25"
    },
    "yi-large": {
        "name": "Yi-Large",
        "link": "https://www.lingyiwanwu.com/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-13"
    },
    "THUDM/codegeex4-all-9b": {
        "name": "CodeGeex4-All-9B",
        "link": "https://huggingface.co/THUDM/codegeex4-all-9b",
        "prompted": True,
        "moe": False,
        "size": 9,
        "act_param": 9,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-05"
    },
    "gpt-4o-mini-2024-07-18": {
        "name": "GPT-4o-mini-2024-07-18",
        "link": "https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-18"
    },
    "Nexusflow/Athene-70B": {
        "name": "Athene-70B",
        "link": "https://huggingface.co/Nexusflow/Athene-70B",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-20"
    },
    "NTQAI/Nxcode-CQ-7B-orpo": {
        "name": "Nxcode-CQ-7B-Orpo",
        "link": "https://huggingface.co/NTQAI/Nxcode-CQ-7B-orpo",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-25"
    },
    "migtissera/Llama-3-70B-Synthia-v3.5": {
        "name": "Llama-3-70B-Synthia-v3.5",
        "link": "https://huggingface.co/migtissera/Llama-3-70B-Synthia-v3.5",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-05-27"
    },
    "migtissera/Tess-v2.5.2-Qwen2-72B": {
        "name": "Tess-v2.5.2-Qwen2-72B",
        "link": "https://huggingface.co/migtissera/Tess-v2.5.2-Qwen2-72B",
        "prompted": True,
        "moe": False,
        "size": 72,
        "act_param": 72,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-18"
    },
    "WhiteRabbitNeo/WhiteRabbitNeo-33B-v1.5": {
        "name": "WhiteRabbitNeo-33B-v1.5",
        "link": "https://huggingface.co/WhiteRabbitNeo/WhiteRabbitNeo-33B-v1.5",
        "prompted": True,
        "moe": False,
        "size": 33,
        "act_param": 33,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-02-10"
    },
    "mistral-large-2407": {
        "name": "Mistral-Large-Instruct-2407",
        "link": "https://huggingface.co/mistralai/Mistral-Large-Instruct-2407",
        "prompted": True,
        "moe": False,
        "size": 123,
        "act_param": 123,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-07-24"
    },
    "meta-llama/Meta-Llama-3.1-8B-Instruct": {
        "name": "Llama-3.1-8B-Instruct",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 8,
        "act_param": 8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-23"
    },
    "meta-llama/Meta-Llama-3.1-70B-Instruct": {
        "name": "Llama-3.1-70B-Instruct",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3.1-70B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-23"
    },
    "meta--llama-3.1-405b-instruct": {
        "name": "Llama-3.1-405B-Instruct",
        "link": "https://huggingface.co/meta-llama/Meta-Llama-3.1-405B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 405,
        "act_param": 405,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-23"
    },
    "deepseek-coder-20240724": {
        "name": "DeepSeek-Coder-V2-Instruct (2024-07-24)",
        "link": "https://www.deepseek.com/",
        "prompted": True,
        "moe": True,
        "size": 236,
        "act_param": 21,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-24"
    },
    "microsoft/Phi-3.5-mini-instruct": {
        "name": "Phi-3.5-Mini-Instruct",
        "link": "https://huggingface.co/microsoft/Phi-3.5-mini-instruct",
        "prompted": True,
        "moe": False,
        "size": 3.8,
        "act_param": 3.8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-23"
    },
    "nv-mistralai--mistral-nemo-12b-instruct": {
        "name": "Mistral-Nemo-12B-Instruct",
        "link": "https://huggingface.co/nv-mistralai/Mistral-Nemo-12B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 12,
        "act_param": 12,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-07-18"
    },
    "wyt2000/InverseCoder-CL-13B": {
        "name": "InverseCoder-CL-13B",
        "link": "https://huggingface.co/wyt2000/InverseCoder-CL-13B",
        "prompted": True,
        "moe": False,
        "size": 13,
        "act_param": 13,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-07-08"
    },
    "wyt2000/InverseCoder-CL-7B": {
        "name": "InverseCoder-CL-7B",
        "link": "https://huggingface.co/wyt2000/InverseCoder-CL-7B",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-07-08"
    },
    "wyt2000/InverseCoder-DS-6.7B": {
        "name": "InverseCoder-DS-6.7B",
        "link": "https://huggingface.co/wyt2000/InverseCoder-DS-6.7B",
        "prompted": True,
        "moe": False,
        "size": 6.7,
        "act_param": 6.7,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-07-08"
    },
    "gemini-1.5-pro-exp-0801": {
        "name": "Gemini-1.5-Pro-Exp-0801",
        "link": "https://deepmind.google/technologies/gemini/pro",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-08-01"
    },
    "gpt-4o-2024-08-06": {
        "name": "GPT-4o-2024-08-06",
        "link": "https://openai.com/index/introducing-structured-outputs-in-the-api/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-08-06"
    },
    "abacusai/Dracarys-Llama-3.1-70B-Instruct": {
        "name": "Dracarys-Llama-3.1-70B-Instruct",
        "link": "https://huggingface.co/abacusai/Dracarys-Llama-3.1-70B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-08-23"
    },
    "abacusai/Dracarys-72B-Instruct": {
        "name": "Dracarys-72B-Instruct",
        "link": "https://huggingface.co/abacusai/Dracarys-72B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 72,
        "act_param": 72,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-08-23"
    },
    "gemini-1.5-pro-exp-0827": {
        "name": "Gemini-1.5-Pro-Exp-0827",
        "link": "https://deepmind.google/technologies/gemini/pro",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-08-27"
    },
    "gemini-1.5-flash-exp-0827": {
        "name": "Gemini-1.5-Flash-Exp-0827",
        "link": "https://deepmind.google/technologies/gemini/flash/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-08-27"
    },
    "microsoft/Phi-3.5-mini-instruct": {
        "name": "Phi-3.5-Mini-Instruct",
        "link": "https://huggingface.co/microsoft/Phi-3.5-mini-instruct",
        "prompted": True,
        "moe": False,
        "size": 3.8,
        "act_param": 3.8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-23"
    },
    "abacusai/Dracarys-Llama-3.1-70B-Instruct": {
        "name": "Dracarys-Llama-3.1-70B-Instruct",
        "link": "https://huggingface.co/abacusai/Dracarys-Llama-3.1-70B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-23"
    },
    "abacusai/Dracarys-72B-Instruct": {
        "name": "Dracarys-72B-Instruct",
        "link": "https://huggingface.co/abacusai/Dracarys-72B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 72,
        "act_param": 72,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-04-23"
    },
    "deepseek-coder-v2.5": {
        "name": "DeepSeek-V2.5",
        "link": "https://www.deepseek.com/",
        "prompted": True,
        "moe": True,
        "size": 236,
        "act_param": 21,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-18"
    },
    "CohereForAI/c4ai-command-r-08-2024": {
        "name": "C4AI-Command-R-08-2024",
        "link": "https://huggingface.co/CohereForAI/c4ai-command-r-08-2024",
        "prompted": True,
        "moe": False,
        "size": 32.3,
        "act_param": 32.3,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-08-30"
    },
    "CohereForAI/c4ai-command-r-plus-08-2024": {
        "name": "C4AI-Command-R-Plus-08-2024",
        "link": "https://huggingface.co/CohereForAI/c4ai-command-r-plus-08-2024",
        "prompted": True,
        "moe": False,
        "size": 104,
        "act_param": 104,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-08-30"
    },
    "ayueei--yue-coder-9b-preview": {
        "name": "Yi-Coder-9B-Chat",
        "link": "https://huggingface.co/01-ai/Yi-Coder-9B-Chat",
        "prompted": True,
        "moe": False,
        "size": 9,
        "act_param": 9,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-04"
    },
    # "mattshumer/ref_70_e3_prefill": {
    #     "name": "Reflection-Llama-3.1-70B",
    #     "link": "https://huggingface.co/mattshumer/ref_70_e3",
    #     "prompted": True,
    #     "moe": False,
    #     "size": 70,
    #     "act_param": 70,
    #     "open-data": "None",
    # },
    # "mattshumer/ref_70_e3": {
    #     "name": "Reflection-Llama-3.1-70B (Recommended Settings)",
    #     "link": "https://huggingface.co/mattshumer/ref_70_e3",
    #     "prompted": True,
    #     "moe": False,
    #     "size": 70,
    #     "act_param": 70,
    #     "open-data": "None",
    # },
    "o1-preview-2024-09-12": {
        "name": "o1-Preview-2024-09-12 (temperature=1)",
        "link": "https://openai.com/index/introducing-openai-o1-preview/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-09-12"
    },
    "o1-mini-2024-09-12": {
        "name": "o1-Mini-2024-09-12 (temperature=1)",
        "link": "https://openai.com/index/introducing-openai-o1-preview/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-09-12"
    },
    "Qwen/Qwen2.5-Coder-1.5B-Instruct": {
        "name": "Qwen2.5-Coder-1.5B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 1.5,
        "act_param": 1.5,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-11-12"
    },
    "Qwen/Qwen2.5-Coder-7B-Instruct": {
        "name": "Qwen2.5-Coder-7B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-11-12"
    },
    "gemini-1.5-pro-002": {
        "name": "Gemini-1.5-Pro-002",
        "link": "https://deepmind.google/technologies/gemini/pro",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-09-25"
    },
    "mistralai/Mistral-Small-Instruct-2409": {
        "name": "Mistral-Small-Instruct-2409",
        "link": "https://huggingface.co/mistralai/Mistral-Small-Instruct-2409",
        "prompted": True,
        "moe": False,
        "size": 22.2,
        "act_param": 22.2,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-18"
    },
    "Qwen/Qwen2.5-0.5B-Instruct": {
        "name": "Qwen2.5-0.5B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 0.5,
        "act_param": 0.5,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-19"
    },
    "Qwen/Qwen2.5-1.5B-Instruct": {
        "name": "Qwen2.5-1.5B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 1.5,
        "act_param": 1.5,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-19"
    },
    "Qwen/Qwen2.5-7B-Instruct": {
        "name": "Qwen2.5-7B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-19"
    },
    "Qwen/Qwen2.5-14B-Instruct": {
        "name": "Qwen2.5-14B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-14B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 14,
        "act_param": 14,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-19"
    },
    "Qwen/Qwen2.5-32B-Instruct": {
        "name": "Qwen2.5-32B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-32B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 32,
        "act_param": 32,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-19"
    },
    "Qwen/Qwen2.5-72B-Instruct": {
        "name": "Qwen2.5-72B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 72,
        "act_param": 72,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-19"
    },
    "meta-llama/Llama-3.2-1B-Instruct": {
        "name": "Llama-3.2-1B-Instruct",
        "link": "https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 1,
        "act_param": 1,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-25"
    },
    "meta-llama/Llama-3.2-3B-Instruct": {
        "name": "Llama-3.2-3B-Instruct",
        "link": "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 3,
        "act_param": 3,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-25"
    },
    "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF": {
        "name": "Llama-3.1-Nemotron-70B-Instruct",
        "link": "https://huggingface.co/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "Partial",
        "reasoning": False,
        "date": "2024-09-25"
    },
    "claude-3-5-sonnet-20241022": {
        "name": "Claude-3.5-Sonnet-20241022",
        "link": "https://claude.ai/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-10-22"
    },
    "ibm-granite/granite-3.0-8b-instruct": {
        "name": "Granite-3.0-8B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-3.0-8b-instruct",
        "prompted": True,
        "moe": False,
        "size": 8,
        "act_param": 8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-10-21"
    },
    "ibm-granite/granite-3.0-2b-instruct": {
        "name": "Granite-3.0-2B-Instruct",
        "link": "https://huggingface.co/ibm-granite/granite-3.0-2b-instruct",
        "prompted": True,
        "moe": False,
        "size": 2,
        "act_param": 2,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-10-21"
    },
    "grok-beta--main": {
        "name": "Grok-Beta",
        "link": "https://grok.com/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-03-17"
    },
    "claude-3-5-haiku-20241022--main": {
        "name": "Claude-3.5-Haiku-20241022",
        "link": "https://claude.ai/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-10-22"
    },
    "Qwen/Qwen2.5-Coder-14B-Instruct--main": {
        "name": "Qwen2.5-Coder-14B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-Coder-14B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 14,
        "act_param": 14,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-19"
    },
    "Qwen/Qwen2.5-Coder-32B-Instruct--main": {
        "name": "Qwen2.5-Coder-32B-Instruct",
        "link": "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 32,
        "act_param": 32,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-09-19"
    },
    "infly/OpenCoder-1.5B-Instruct--main": {
        "name": "OpenCoder-1.5B-Instruct",
        "link": "https://huggingface.co/infly/OpenCoder-1.5B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 1.5,
        "act_param": 1.5,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-11-09"
    },
    "infly/OpenCoder-8B-Instruct--main": {
        "name": "OpenCoder-8B-Instruct",
        "link": "https://huggingface.co/infly/OpenCoder-8B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 8,
        "act_param": 8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-11-09"
    },
    "microsoft/Phi-3.5-mini-instruct--main": {
        "name": "Phi-3.5-Mini-Instruct",
        "link": "https://huggingface.co/microsoft/Phi-3.5-mini-instruct",
        "prompted": True,
        "moe": False,
        "size": 3.8,
        "act_param": 3.8,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-08-21"
    },
    "Nexusflow/Athene-V2-Agent--main": {
        "name": "Athene-V2-Agent",
        "link": "https://huggingface.co/Nexusflow/Athene-V2-Agent",
        "prompted": True,
        "moe": False,
        "size": 72,
        "act_param": 72,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-11-14"
    },
    "Nexusflow/Athene-V2-Chat--main": {
        "name": "Athene-V2-Chat",
        "link": "https://huggingface.co/Nexusflow/Athene-V2-Chat",
        "prompted": True,
        "moe": False,
        "size": 72,
        "act_param": 72,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-11-14"
    },
    "gemini-exp-1114--main": {
        "name": "Gemini-Exp-1114",
        "link": "https://deepmind.google/technologies/gemini",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-11-14"
    },
    "gpt-4o-2024-11-20--main": {
        "name": "GPT-4o-2024-11-20",
        "link": "https://openai.com/gpt-4o/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-11-20"
    },
    "gemini-exp-1121--main": {
        "name": "Gemini-Exp-1121",
        "link": "https://deepmind.google/technologies/gemini",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-11-21"
    },
    "gemini-exp-1206--main": {
        "name": "Gemini-Exp-1206",
        "link": "https://deepmind.google/technologies/gemini",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-12-06"
    },
    "meta-llama--Llama-3.3-70B-Instruct--main": {
        "name": "Llama-3.3-70B-Instruct",
        "link": "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-12-19"
    },
    "deepseek-ai--DeepSeek-V2.5-1210--main": {
        "name": "DeepSeek-V2.5-1210",
        "link": "deepseek-ai/DeepSeek-V2.5-1210",
        "prompted": True,
        "moe": True,
        "size": 236,
        "act_param": 21,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-12-10"
    },
    "gemini-2.0-flash-exp--main": {
        "name": "Gemini-2.0-Flash-Exp",
        "link": "https://deepmind.google/technologies/gemini",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-12-11"
    },
    "gemini-2.0-flash-thinking-exp-1219--main": {
        "name": "Gemini-2.0-Flash-Thinking-Exp-1219",
        "link": "https://deepmind.google/technologies/gemini",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-12-19"
    },
    "gemini-2.0-flash-thinking-exp-01-21--main": {
        "name": "Gemini-2.0-Flash-Thinking-Exp-01-21",
        "link": "https://deepmind.google/technologies/gemini",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-21"
    },
    "o1-2024-12-17--main": {
        "name": "o1-2024-12-17 (temperature=1, reasoning=medium)",
        "link": "https://openai.com/o1/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-12-17"
    },
    "o1-2024-12-17--low--main": {
        "name": "o1-2024-12-17 (temperature=1, reasoning=low)",
        "link": "https://openai.com/o1/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-12-17"
    },
    "o1-2024-12-17--high--main": {
        "name": "o1-2024-12-17 (temperature=1, reasoning=high)",
        "link": "https://openai.com/o1/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-12-17"
    },
    "deepseek-v3-chat--main": {
        "name": "DeepSeek-V3",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-V3",
        "prompted": True,
        "moe": True,
        "size": 671,
        "act_param": 37,
        "open-data": "None",
        "reasoning": True,
        "date": "2024-12-26"
    },
    "microsoft--phi-4--main": {
        "name": "Phi-4",
        "link": "https://huggingface.co/microsoft/phi-4",
        "prompted": True,
        "moe": False,
        "size": 14.7,
        "act_param": 14.7,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-12-13"
    },
    "deepseek-reasoner--main": {
        "name": "DeepSeek-R1",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-R1",
        "prompted": True,
        "moe": True,
        "size": 671,
        "act_param": 37,
        "open-data": "None",
        "reasoning": True,
        "date": "2025-01-20"
    },
    "deepseek-ai/DeepSeek-R1-Distill-Llama-70B--main": {
        "name": "DeepSeek-R1-Distill-Llama-70B",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
        "prompted": True,
        "moe": False,
        "size": 70,
        "act_param": 70,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-20"
    },
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B--main": {
        "name": "DeepSeek-R1-Distill-Qwen-32B",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
        "prompted": True,
        "moe": False,
        "size": 32,
        "act_param": 32,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-20"
    },
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B--main": {
        "name": "DeepSeek-R1-Distill-Qwen-14B",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
        "prompted": True,
        "moe": False,
        "size": 14,
        "act_param": 14,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-20"
    },
    "deepseek-ai/DeepSeek-R1-Distill-Llama-8B--main": {
        "name": "DeepSeek-R1-Distill-Llama-8B",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
        "prompted": True,
        "moe": False,
        "size": 8,
        "act_param": 8,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-20"
    },
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B--main": {
        "name": "DeepSeek-R1-Distill-Qwen-7B",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
        "prompted": True,
        "moe": False,
        "size": 7,
        "act_param": 7,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-20"
    },
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B--main": {
        "name": "DeepSeek-R1-Distill-Qwen-1.5B",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
        "prompted": True,
        "moe": False,
        "size": 1.5,
        "act_param": 1.5,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-20"
    },
    "mistralai/Mistral-Small-24B-Instruct-2501--main": {
        "name": "Mistral-Small-24B-Instruct-2501",
        "link": "https://huggingface.co/mistralai/Mistral-Small-24B-Instruct-2501",
        "prompted": True,
        "moe": False,
        "size": 24,
        "act_param": 24,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-31"
    },
    "o3-mini-2025-01-31--medium--main": {
        "name": "o3-mini-2025-01-31 (temperature=1, reasoning=medium)",
        "link": "https://openai.com/index/openai-o3-mini/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2025-01-31"
    },
    "o3-mini-2025-01-31--low--main": {
        "name": "o3-mini-2025-01-31 (temperature=1, reasoning=low)",
        "link": "https://openai.com/index/openai-o3-mini/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2025-01-31"
    },
    "o3-mini-2025-01-31--high--main": {
        "name": "o3-mini-2025-01-31 (temperature=1, reasoning=high)",
        "link": "https://openai.com/index/openai-o3-mini/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2025-01-31"
    },
    "gemini-2.0-flash-001--main": {
        "name": "Gemini-2.0-Flash-001",
        "link": "https://blog.google/technology/google-deepmind/gemini-model-updates-february-2025/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-02-05"
    },
    "gemini-2.0-flash-exp--main": {
        "name": "Gemini-2.0-Flash-Exp",
        "link": "https://blog.google/technology/google-deepmind/gemini-model-updates-february-2025/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-02-05"
    },
    "gemini-2.0-flash-lite-preview-02-05--main": {
        "name": "Gemini-2.0-Flash-Lite-Preview-02-05",
        "link": "https://blog.google/technology/google-deepmind/gemini-model-updates-february-2025/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-02-05"
    },
    "gemini-2.0-pro-exp-02-05--main": {
        "name": "Gemini-2.0-Pro-Exp-02-05",
        "link": "https://blog.google/technology/google-deepmind/gemini-model-updates-february-2025/",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-02-05"
    },
    "NovaSky-AI--Sky-T1-32B-Flash--main": {
        "name": "Sky-T1-32B-Flash",
        "link": "https://huggingface.co/NovaSky-AI/Sky-T1-32B-Flash",
        "prompted": True,
        "moe": False,
        "size": 32,
        "act_param": 32,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-12"
    },
    "NovaSky-AI--Sky-T1-32B-Preview--main": {
        "name": "Sky-T1-32B-Preview",
        "link": "https://huggingface.co/NovaSky-AI/Sky-T1-32B-Preview",
        "prompted": True,
        "moe": False,
        "size": 32,
        "act_param": 32,
        "open-data": "None",
        "reasoning": False,
        "date": "2025-01-12"
    },
    "Qwen--QwQ-32B-Preview--main": {
        "name": "QwQ-32B-Preview",
        "link": "https://huggingface.co/Qwen/QwQ-32B-Preview",
        "prompted": True,
        "moe": False,
        "size": 32,
        "act_param": 32,
        "open-data": "None",
        "reasoning": False,
        "date": "2024-11-28"
    },
    "claude-3-7-sonnet-20250219--main": {
        "name": "Claude-3-Haiku-20240307",
        "link": "https://www.anthropic.com/news/claude-3-family",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2025-02-19"
    },
    "chatgpt-4o-latest--main": {
        "name": "ChatGPT-4o-latest-20250129",
        "link": "https://chat.openai.com/",
        "open-data": "None",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "date": "2025-01-29"
    },
    "Kwaipilot--KwaiCoder-23B-A4B-v1--main": {
        "name": "KwaiCoder-23B-A4B-v1",
        "link": "https://huggingface.co/Kwaipilot/KwaiCoder-23B-A4B-v1",
        "open-data": "None",
        "prompted": False,
        "moe": True,
        "size": 23,
        "act_param": 4,
        "date": "2025-01-25"
    },
    "qwen-max-latest--main": {
        "name": "Qwen2.5-Max",
        "link": "https://qwenlm.github.io/blog/qwen2.5-max/",
        "open-data": "None",
        "prompted": True,
        "moe": True,
        "size": None,
        "act_param": None,
        "date": "2025-01-28"
    },
    "claude-3-7-sonnet-20250219--3200-output-128k-2025-02-19--main": {
        "name": "Claude-3.7-Sonnet-20250219 (temperature=1, length=12800, reasoning=3200)",
        "link": "https://www.anthropic.com/news/claude-3-7-sonnet",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2025-02-19"
    },
    "claude-3-7-sonnet-20250219--main": {
        "name": "Claude-3.7-Sonnet-20250219",
        "link": "https://www.anthropic.com/news/claude-3-7-sonnet",
        "prompted": True,
        "moe": False,
        "size": None,
        "act_param": None,
        "open-data": "None",
        "reasoning": True,
        "date": "2025-02-19"
    },
    "WarriorCoder-6.7B--main": {
        "name": "WarriorCoder-6.7B (Reproduced)",
        "link": "https://arxiv.org/abs/2412.17395",
        "open-data": "None",
        "prompted": True,
        "moe": False,
        "date": "2025-02-18"
    },
    "google--gemma-3-27b-it--main": {
        "name": "Gemma-3-27B-Instruct",
        "link": "https://huggingface.co/google/gemma-3-27b-it",
        "open-data": "None",
        "prompted": True,
        "moe": False,
        "date": "2025-03-12"
    },
    "Qwen--QwQ-32B--skip_prefill--main": {
        "name": "QwQ-32B (w/ Reasoning)",
        "link": "https://huggingface.co/Qwen/QwQ-32B",
        "open-data": "None",
        "prompted": True,
        "moe": False,
        "date": "2025-03-06"
    },
    "deepseek-chat-0324--main": {
        "name": "DeepSeek-V3-0324",
        "link": "https://huggingface.co/deepseek-ai/DeepSeek-V3-0324",
        "open-data": "None",
        "prompted": True,
        "moe": False,
        "date": "2025-03-24"
    }
}
